# Generated by Django 4.2.1 on 2023-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_therapist_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='post',
            field=models.CharField(default='patient', max_length=200),
        ),
    ]
