# Generated by Django 4.2.1 on 2023-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_patient_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='post',
            field=models.CharField(default='patient', max_length=200, null=True),
        ),
    ]
